import sys
import random
print('-' * 30, ' sys & random ', '-' * 30)
print('OS is : ', sys.platform)
print('Random number is : ', random.random())
print('Random choice is : ', random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))
print('-' * 30, ' String ', '-' * 30)
s = 'Spam'
print('s length is : ', len(s))
print(s[2])
print(s[1:3])
print(s[:3])
print(s[:])
l = list(s)
print(l)
print(','.join(l))
print(s.find('pa'))
print(s.replace('pa', 'xy'))
print(s)
s = 'aaa,bbb,ccc'
l = s.split(',')
print(l)
s = 'abc\n'
print(s)
print(s.rstrip())
print('lower is : %s, upper is : %s.' %('spam','SPAM'))
print('lower is : {0}, upper is : {1}.'.format('spam','SPAM'))
print('lower is : {}, upper is : {}.'.format('spam','SPAM'))
print('-' * 30, ' List ', '-' * 30)
l = [1,2,3]
print(len(l))
l.append(4)
print(l)
i = 0
while i < len(l):
	print('Element is : ', l[i])
	i += 1
print(l.pop())
print(l.pop(1))
print(l)
l.append(5)
l.append(4)
l.append(9)
l.append(7)
l.append(6)
print(l)
print('from zero to four : ', l[:4])
print('from two to the end : ', l[2:])
l.sort()
print(l)
l.reverse()
print(l)
s = 'abcdefg'
l = list(s)
print(l)
l = list(range(1,10,2))
print(l)
l = [[x * 2, x * 3] for x in range(5)]
print(l)
l = [ord(x) for x in 'spam']
print(l)
print('-' * 30, ' Set ', '-' * 30)
s1 = {'a','b','c','x','y','z'}
s2 = set('abcdef')
print('s1 is : ', s1)
print('s2 is : ', s2)
print('the same elements are : ', s1 & s2)
print('all elements are : ', s1 | s2)
print('differente elements are : ', s1 - s2)
l = [1,2,3,4,2,2,2,4,5,6,5,3,3,1,1]
print(l)
l = list(set(l))
print(l)
print('-' * 30, ' Dictionaries ', '-' * 30)
d1 = {'e':5,'d':4,'a':1,'b':2,'c':3}
print(d1)
d2 = dict(name='Harry',age=35,job='IT')
print(d2)
d3 = dict(zip(['name','age','job'],['Jack',35,'IT']))
print(d3)
ks = list(d1.keys())
print(ks)
ks.sort()
for k in ks : 
	print('Key is : ', k, ' value is : ', d1[k])
for k in sorted(d1):
	print('Key is : ', k, ' value is : ', d1[k])
fv = d3.get('favor','Movies')
print(d3)
print(fv)
print('-' * 30, ' Tuples ', '-' * 30)
tp = (1,2,3,4,5,6,3,4,5,2,1)
for e in tp:
	print('Tuple element is : ', e)
print('The first element is : ', tp[0])
print('The second element is : ', tp[1])
print('Element 4 index is : ', tp.index(4))
print('Element 6 index is : ', tp.index(6))
print('5 count is : ', tp.count(5))
print('-' * 30, ' Files ', '-' * 30)
f = open('data.txt')
print(f.readline())
print('-' * 80)
for line in f:
	print(line)
f.close()
f = open('new.txt','w')
f.write("This is a new file.\n")
f.write("It is created by Python.")
f.close()
print('-' * 80)