import pickle
import json
import csv
print('-' * 80)
afile = open('file.txt')
print(afile)
print(afile.readlines())
print(afile.readline())
afile.close()
print('-' * 80)
for line in open('file.txt'):
	print('Line content : ', line)
print('-' * 80)
myfile = open('myfile.txt','w')
cs = 0
cs = myfile.write('hello text fle\n')
print(cs)
cs = myfile.write('goodbye text file\n')
print(cs)
myfile.close()
cns = open('myfile.txt').read()
print(cns)
myfile.close()
print('-' * 80)
x,y,z=43,44,45
s = 'Spam'
d = {'a':1,'b':2}
l = [1,2,3]
f = open('datafile.txt','w')
f.write(s + '\n')
f.write('%s,%s,%s\n' % (x,y,z))
f.write(str(l)+'$'+str(d)+'\n')
f.close()
f = open('datafile.txt')
chars = f.read()
print(chars)
f.close()
f = open('datafile.txt')
line = f.readline()
print(line)
print(line.rstrip())
line = f.readline()
print(line)
strs = line.split(',')
print(strs)
nums = [int(n) for n in strs]
print(nums)
strs = f.readline()
print(strs)
parts = strs.split('$')
print(parts)
objs = [eval(p) for p in parts]
print(objs)
print('-' * 80)
d = {'a':1,'b':2,'c':3}
f = open('datafile.pkl','wb')
pickle.dump(d,f)
f.close()
f = open('datafile.pkl', 'rb')
d = pickle.load(f)
print(d)
f.close()
print('-' * 80)
name = dict(first='Guoqian',last='Cheng')
rec = dict(name=name,jobs=['Dev','Mgr'],age=35)
print('dictionary : ',rec)
s = json.dumps(rec)
print('from dictionary to json object : ',s)
o = json.loads(s)
print('dictionary(from json object to dictionary) : ',o)
print('Write the json object to the file now ...')
json.dump(rec, open('jsondata.txt','w'),indent=4)
p = json.load(open('jsondata.txt'))
print('loaded from the file : ' , p)
print('-' * 80)
#CSV (comma-separated value)
rdr = csv.reader(open('csvdata.txt'))
for row in rdr:
	print(row)
print('-' * 80)