import struct
print('-' * 80)
f = open('data.bin','wb')
data = struct.pack('>i4sh',7,b'spam',8)
f.write(data)
f.close()
f = open('data.bin','rb')
data = f.read()
values = struct.unpack('>i4sh', data)
print(values)
print('-' * 80)