import struct
print('-' * 80)
packed = struct.pack('>i4sh', 7, b'spam', 8)
print('Write content into the data.bin file', packed)
file = open('data.bin', 'wb')
file.write(packed)
file.close()
print('-' * 80)
data = open('data.bin', 'rb').read()
print('Read from the data.bin file : ',data)
print('-' * 80)
print(data[4:8])
print('-' * 80)
l = list(data)
print(l)
for e in l:
	print('The element is : ', e)
print('-' * 80)
s = struct.unpack('>i4sh', data)
print(s)
print('-' * 80)