import re
print('=' * 180)
p = re.compile('www')
print(type(p))
m1 = re.match(p,'www.fkit.org')
print(type(m1))
print(m1.span())
print(m1.group())
print(re.match('fkit','www.fkit.org'))
print('-' * 80)
m2 = re.search('www','www.fkit.org')
print(type(m2))
print(m2.span())
print(m2.group())
print('-' * 80)
m3 = re.search('fkit','www.fkit.org')
print(m3.span())
print(m3.group())
print('-' * 80)
r = re.findall('fkit','Fkit is good, I like the fkit and the Fkit.org web',re.I)
print(type(r))
print(r)
r = re.finditer('fkit','Fkit is good, I like the fkit and the Fkit.org web',re.I)
print(type(r))
for e in r:
    print(e.span() ,'-->',e.group())
print('-' * 80)
my_date = '2020-04-24'    
print('Date string : ', my_date)
print(re.sub(r'-','/',my_date))
my_str = 'Java is a good language , and the Python too'
print('String : ', my_str)
print(re.sub(r'o', 'u', my_str))
my_str = 'a,b,c,d,e,f'
my_list = my_str.split(',')
print(my_list)
r = re.split(',', my_str)
print(type(r))
print(r)
print('-' * 80)
print(re.escape(r'www.crazyit.org is good, and I love it'))
print(re.escape(r'A-Zand0_9?'))
print('-' * 80)
#正则表达式对象 - pattern 
#match对象 - match
pa = re.compile('fkit')
print(pa.match('www.fkit.org', 4).span())
print(pa.match('www.fkit.org', 4, 6))
print(pa.fullmatch('www.fkit.org', 4,8).span())
print(pa.fullmatch('www.fkit.org', 4,8).start())
print(pa.fullmatch('www.fkit.org', 4,8).end())
#组：用圆括号将多个表达式括起来就是一个组，如果没有圆括号，那么整个表达式就是一个默认组
m = re.search(r'(fkit).(org)',r'www.fkit.org is a good domain')
print(m.groups())
print(len(m.groups()))
print(m.group(0))
print(m.span(0))
print(m[0])
print(m[1])
print(m[2])
print(m.group(2))
m2 = re.search(r'(?P<prefix>fkit).(?P<suffix>org)', r'www.fkit.org is a good domain')
print(m2.groupdict())
print('-' * 80)
print(re.findall(r'fkit','Fkit is a good domain, FKIT is good'))
print(re.findall(r'fkit','Fkit is a good domain, FKIT is good',re.I))
print('-' * 80)
#创建正则表达式

print('=' * 180)