import sys
print('-' * 80)
l1 = len(dir(sys))
print('sys length is : ', l1)
print('-' * 80)
l2 = len([x for x in dir(sys) if not x.startswith('__')])
print(l2)
print('-' * 80)
l3 = len([x for x in dir(sys) if not x[0] == '_'])
print(l3)
print('-' * 80)
print(dir(sys))
print('-' * 80)
lst = dir([])
print('list methods are : ')
print(lst)
print('-' * 80)
sts = dir('')
print('string methods are : ')
print(sts)
print(len(lst), len([x for x in dir([]) if not x.startswith('__')]))
print(len(sts), len([x for x in dir('') if not x.startswith('__')]))
print('-' * 80)
def getdirs(x):
	return [e for e in dir(x) if not e.startswith('__')]
print(getdirs(tuple))
print('-' * 80)