from collections import namedtuple
print('-' * 80)
t1 = (1,2)
t2 = (3,4)
t3 = t1 + t2
print(t3)
print(t1 * 4)
print(t3[1])
print(t3[1:3])
t = (40)
print(t)
t = (40,)
print(t)
print('-' * 80)
t = ('cc','aa','dd','bb')
tl = list(t)	# Make a list from a tuple's items
tl.sort()		# Sort the list
print(tl)
t = tuple(tl)	# Make a tuple from the list's items
print(t)
t = ('cc','aa','dd','bb')
print(sorted(t))	# Or use the sorted built-in, and save two steps
print('-' * 80)
t = (1,2,3,4,5)
l = [x + 20 for x in t]
print(l)
print('-' * 80)
t = (1,2,3,2,4,2)
i = t.index(2)
print('index is : ', i)
i = t.index(2,2)
print('index is : ', i)
c = t.count(2)
print('There is ', c , '2s in the tuple.')
print('-' * 80)
t = (1,[2,3],4)
#t[1] = 'spam'		# This fails: can't change tuple itself
t[1][0] = 'spam'	# This works: can change mutables inside
print(t)
print('-' * 80)
bob = ('Bob',45,['dev','mgr'])
print(bob)
print(bob[0])
print(bob[2])
print('-' * 80)
rec = namedtuple('Rec',['name','age','jobs'])
bob = rec(name='Bob',age=40.5,jobs=['dev','mgr'])
print(bob)
print(bob[0])
print(bob[2])
print(bob.name)
print(bob.jobs)
d = bob._asdict()
print(d)
print(d['name'])
print(d['jobs'])
print('-' * 80)